config:
  bind: 0.0.0.0:25565
  onlineMode: true
  servers:
    lobby: lobby:25565
    survival: survival:25565
  try:
    - lobby
  status:
    motd: |
      §aOreForge Example Network v4
      §7Powered by Gate
  forwarding:
    mode: velocity
    velocitySecret: ore-testnet-forwarding-secret
