online-mode=false
server-port=25565
motd=Survival
max-players=50
difficulty=normal
gamemode=survival
pvp=true
spawn-monsters=true
spawn-animals=true
spawn-npcs=true
allow-nether=true
level-name=world
level-type=normal
generate-structures=true
view-distance=12
simulation-distance=8
max-world-size=10000
